Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    
### DB vm ###
    config.vm.define "db01" do |db01|
        db01.vm.box = "centos/stream9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.70"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end

### Memcache vm ###
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "centos/stream9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.71"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end

### RabbitMQ vm ###
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "centos/stream9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.72"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end

### Tomcat vm ###
    config.vm.define "app01" do |app01|
        app01.vm.box = "centos/stream9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.73"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
        end
    end

### NginX vm ###
    config.vm.define "web01" do |web01|
        web01.vm.box = "centos/stream9"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.74"
        web01.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.memory = "1024"
        end
    end

end